### ISSUE TITLE
Incompatible with Minecraft 1.17.

### ISSUE THREAD

**Issue by RealTriassic** [Kurumi78/Bush#1]
[13:02:37 ERROR]: Could not pass event PlayerInteractEvent to Bush v1.1
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.bukkit.event.player.PlayerInteractEvent.getClickedBlock()" is null
        at com.gmail.kurumi78.bush.events.BushClick.OnBushClick(BushClick.java:18) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor37.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Purpur-1240]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Purpur-1240]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Purpur-1240]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Purpur-1240]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:538) ~[patched_1.17.jar:git-Purpur-1240]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[patched_1.17.jar:git-Purpur-1240]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:496) ~[patched_1.17.jar:git-Purpur-1240]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1924) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1414) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1392) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1469) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1262) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1240]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Kurumi78** [comment]
Huh, strange. Ill look into this
